$(function(){
    $(".li1").click(function(){
        $(this).addClass("active").siblings().removeClass("active") 
        $(".li1-nr").show()
        $(".li1-nr").siblings().hide()
    })
    $(".li2").click(function(){
        $(this).addClass("active").siblings().removeClass("active")
        $(".li2-nr").show()
        $(".li2-nr").siblings().hide()
    })
    $(".li3").click(function(){
        $(this).addClass("active").siblings().removeClass("active")
        $(".li3-nr").show()
        $(".li3-nr").siblings().hide()
    })
    $(".li4").click(function(){
        $(this).addClass("active").siblings().removeClass("active")
        $(".li4-nr").show()
        $(".li4-nr").siblings().hide()
    })
    $(".li5").click(function(){
        $(this).addClass("active").siblings().removeClass("active")
        $(".li5-nr").show()
        $(".li5-nr").siblings().hide()
    })
    $(".pn-li1").click(function(){
        $(".li1-nr").show()
        $(".li1-nr").siblings().hide()
    })
    $(".pn-li2").click(function(){
        $(".li2-nr").show()
        $(".li2-nr").siblings().hide()
    })
    $(".pn-li3").click(function(){
        $(".li3-nr").show()
        $(".li3-nr").siblings().hide()
    })
    $(".pn-li4").click(function(){
        $(".li4-nr").show()
        $(".li4-nr").siblings().hide()
    })
    $(".pn-li5").click(function(){
        $(".li5-nr").show()
        $(".li5-nr").siblings().hide()
    })
    $(".phone-nav").click(function(){
        $(".phone-nav .pn-ul").fadeToggle()
    })
})